import { fetch } from 'your-fetch-library'; // Import the necessary fetch function/library
import { BASE_URL } from "../pages/api/api_config";
import { IMAGE_URL } from "../pages/api/api_config";
import Head from 'next/head';
import Link from "next/link";
import CategoryPost from "@/components/Home/CategoryPost";
import Gallery from "@/components/Home/gallery";
import PostItem from "@/components/Home/ItemPost"

const IMAGE_URL = 'https://www.admin.pakistaneyes.com/public/storage/';
const BASE_URL = 'http://localhost:3000/';
export async function generateMetadata({ params }, parent) {
  // read route params
  const id = params.id;

  // fetch data
  const post = await fetch(`https://www.admin.pakistaneyes.com/public/storage//${id}`).then((res) => res.json());

  // optionally access and extend (rather than replace) parent metadata
  const IMAGE_URL = (await parent).openGraph?.images || [];

  return {
    title: post.title,
    openGraph: {
      images: ['IMAGE_URL', ...previousImages],
    },
  };
}

// Use the generated metadata in your Next.js page
// export default function Page({ params, searchParams }) {
//   // You can use the metadata generated by generateMetadata here
//   const metadata = await generateMetadata({ params });

//   return (
//     <div>
//       <h1>{metadata.title}</h1>
//       {/* Your page content goes here */}
//     </div>
//   );
// }